import type { Metadata } from 'next'
import './globalStyles/normalize.css'
import './globalStyles/globals.css'
import './globalStyles/header.css'
import './globalStyles/auth-popup.css'
import './globalStyles/header-profile.css'
import PagesLayout from '@/components/layouts/PagesLayout'

export const metadata: Metadata = {
  title: 'Лаборатория интеллектуального анализа данных',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <PagesLayout>{children}</PagesLayout>
}
