import type { Metadata } from 'next'
import PagesLayout from '@/components/layouts/PagesLayout'
import './globalStyles/normalize.css'
import './globalStyles/globals.css'
import './globalStyles/header.css'
import './globalStyles/auth-popup.css'
import './globalStyles/header-profile.css'
import './globalStyles/breadcrumbs.css'

export const metadata: Metadata = {
  title:
    ' ЛИАД | Лаборатория интеллектуального анализа данных КГПИ ФГБОУ ВО "КемГУ"',
  /*description: 'Generated by create next app',*/
  description:
    'Сайт лаборатории интелектуального анализа данных КГПИ ФГБОУ ВО "КемГУ"',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <PagesLayout>{children}</PagesLayout>
}
